[package]
authors = ['GalacticCouncil']
edition = '2018'
name = 'primitives'
version = '2.0.0'

[build-dependencies]
wasm-builder-runner = {package = 'substrate-wasm-builder-runner', version = '1.0.5'}

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
primitive-types = {default-features = false, version = '0.7.2'}
serde = {features = ['derive'], optional = true, version = '1.0.120'}

# Substrate dependencies
frame-support = {default-features = false, version = '2.0.0'}
frame-system = {default-features = false, version = '2.0.0'}
sp-std = {default-features = false, version = '2.0.0'}

[dev-dependencies]
sp-core = {default-features = false, version = '2.0.0'}
sp-io = {default-features = false, version = '2.0.0'}
sp-runtime = {default-features = false, version = '2.0.0'}

[features]
default = ['std']
std = [
  'codec/std',
  'primitive-types/std',
  'serde',
  'frame-support/std',
  'sp-std/std',
]
