[package]
authors = ['GalacticCouncil']
edition = '2018'
name = 'primitives'
version = '1.0.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc5'
version = '2.0.0-rc5'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc5'
version = '2.0.0-rc5'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc5'
version = '2.0.0-rc5'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc5'
version = '2.0.0-rc5'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.primitive-types]
default-features = false
package = 'primitive-types'
version = '0.7.2'

[features]
default = ['std']
std = [
  'frame-support/std',
  'codec/std',
  'serde',
  'sp-std/std',
  'primitive-types/std',
]
