version: "3.2"

services:
  dev:
    container_name: hydra-dx-node
    image: paritytech/ci-linux:production
    working_dir: /hydra-dx-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/hydra-dx-node/.cargo
    volumes:
      - .:/hydra-dx-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/hydra-dx --dev --ws-external"
