[package]
authors = ['GalacticCouncil']
build = 'build.rs'
description = 'Hydra DX'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydradx-node'
license = 'Unlicense'
name = 'hydra-dx'
repository = 'https://github.com/galacticcouncil/hydradx-node'
version = '2.0.0'

[[bin]]
name = 'hydra-dx'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = '2.0.1'

[dependencies]
hex-literal = "0.3.1"
jsonrpc-core = '15.0.0'
serde_json = "1.0.61"
structopt = '0.3.8'

# local dependencies
hydra-dx-runtime = {path = '../runtime', version = '2.0.0'}
module-amm-rpc = {path = '../pallets/amm/rpc', version = '2.0.0'}
primitives = {path = '../primitives', version = '2.0.0'}

# Substrate dependencies
frame-benchmarking = '2.0.0'
frame-benchmarking-cli = {version = '2.0.0', optional = true}
futures = '0.3.4'
pallet-im-online = "2.0.0"
pallet-staking = '2.0.0'
pallet-transaction-payment-rpc = '2.0.0'
sc-authority-discovery = '0.8.0'
sc-basic-authorship = '0.8.0'
sc-cli = {features = ['wasmtime'], version = '0.8.0'}
sc-client-api = '2.0.0'
sc-consensus = '0.8.0'
sc-consensus-babe = '0.8.0'
sc-consensus-babe-rpc = '0.8.0'
sc-consensus-epochs = '0.8.0'
sc-consensus-slots = '0.8.0'
sc-executor = {features = ['wasmtime'], version = '0.8.0'}
sc-finality-grandpa = '=0.8.0'
sc-finality-grandpa-rpc = '=0.8.0'
sc-keystore = '2.0.0'
sc-network = '0.8.0'
sc-rpc = '2.0.0'
sc-rpc-api = '0.8.0'
sc-service = '0.8.0'
sc-transaction-pool = '2.0.0'
sp-api = '2.0.0'
sp-authority-discovery = '2.0.0'
sp-block-builder = '2.0.0'
sp-blockchain = '2.0.0'
sp-consensus = '0.8.0'
sp-consensus-babe = '0.8.0'
sp-core = '=2.0.0'
sp-finality-grandpa = '2.0.0'
sp-inherents = '2.0.0'
sp-keystore = '0.8.0'
sp-runtime = '2.0.0'
sp-transaction-pool = '2.0.0'
sc-telemetry = '2.0.0'
substrate-frame-rpc-system = '2.0.0'

[features]
default = [
  "frame-benchmarking-cli",
]
runtime-benchmarks = [
  'hydra-dx-runtime/runtime-benchmarks',
  "frame-benchmarking-cli",
]
