name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-09-27
          target: wasm32-unknown-unknown
          override: true
          default: true
      - run: ./scripts/init.sh
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --release -- -D warnings
      - name: Tests
        run: time cargo test --all --release --verbose --locked
      - name: Benchmarking tests
        run: cd node && cargo test --release --features runtime-benchmarks -p pallet-exchange-benchmarking -p pallet-amm -p pallet-multi-payment-benchmarking
      - name: Build release
        run: time cargo build --release --verbose
      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: hack-hydra-dx
          path: target/release/hack-hydra-dx
